server:
  host: "0.0.0.0"
  port: 20000
  
database:
  host: "localhost"
  port: 3306
  name: "gamehub_arena"
  user: "root"
  password: "123456"
  
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  
logging:
  level: "info"
  format: "json"