server:
  host: "0.0.0.0"
  port: 20000
  
database:
  host: "localhost"
  port: 5432
  name: "gamehub_arena"
  user: "postgres"
  password: "123456"
  ssl_mode: "disable"
  max_open_conns: 100
  max_idle_conns: 10
  max_lifetime: 1  # 小时
  
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  
logging:
  level: "info"
  format: "json"
  output: "console"
  file_path: "./logs/app.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

auth:
  jwt:
    secret_key: "ctAf9pUx41LkDOJKAG4uz8OhLAAQTOwK"
    access_token_ttl: 15
    refresh_token_ttl: 168
    issuer: "gamehub-arena"
    audience: "gamehub-users"
  password:
    min_length: 8
    require_upper: true
    require_lower: true
    require_digit: true
    require_symbol: false
    bcrypt_cost: 12
  session:
    max_sessions: 5
    inactive_timeout: 30
    remember_me_days: 30

monitoring:
  metrics:
    enabled: true
    port: 9090
    path: /metrics
    namespace: gamehub
    subsystem: arena
  tracing:
    enabled: false
    service_name: gamehub-arena
  health:
    enabled: true
    port: 8080
    path: /health
    check_interval: 30


